// Auth Models
export interface LoginDto {
  email: string;
  password: string;
}

export interface CreateAccountDto {
  id?: string; // Optional ID field - will be generated by backend if not provided
  email: string;
  password: string;
  fullName: string;
  phoneNumber: string;
}

export interface UserDto {
  id: string;
  email: string;
  fullName: string;
  phoneNumber: string;
  role?: string; // Single role string to match API response
  roles?: string[]; // Keep this for backward compatibility if needed
}

export interface UpdateAccountDto {
  fullName: string;
  email: string;
  phoneNumber?: string;
  newPassword?: string;
  confirmNewPassword?: string;
}

export interface SetRoleRequestDto {
  email: string;
  role: string;
}

export interface ChangePasswordDto {
  currentPassword: string;
  newPassword: string;
  confirmNewPassword: string;
}

